---
title: "Questionnaire & My Answers: fastbook"
author: "Oleh Nevidomskyi"
date: "2026-06-17"
categories: [news]
---

This post covers the questionnaires provided at the end of each section of the [fastbook](https://github.com/fastai/fastbook/tree/master) and my answers to them.

I will be updating this page and answering more questions as I move forward with the book.

### 01 Intro:

Do you need these for deep learning?

Lots of math: T / [F]{.mark}

Lots of data: T / [F]{.mark}

Lots of expensive computers: T / [F]{.mark}

A PhD: T / [F]{.mark}

Name five areas where deep learning is now the best in the world.

What was the name of the first device that was based on the principle of the artificial neuron?

Based on the book of the same name, what are the requirements for parallel distributed processing (PDP)?

What were the two theoretical misunderstandings that held back the field of neural networks?

What is a GPU?

Open a notebook and execute a cell containing: 1+1. What happens?

- The cell computes 1+1 and outputs 2.

Why is it hard to use a traditional computer program to recognize images in a photo?

What did Samuel mean by "weight assignment"?

What term do we normally use in deep learning for what Samuel called "weights"?

Draw a picture that summarizes Samuel's view of a machine learning model.

Why is it hard to understand why a deep learning model makes a particular prediction?

What is the name of the theorem that shows that a neural network can solve any mathematical problem to any level of accuracy?

What do you need in order to train a model?

How could a feedback loop impact the rollout of a predictive policing model?

Do we always have to use 224×224-pixel images with the cat recognition model?

What is the difference between classification and regression?

What is a validation set? What is a test set? Why do we need them?

What will fastai do if you don't provide a validation set?

Can we always use a random sample for a validation set? Why or why not?

What is overfitting? Provide an example.

- Overfitting is training a model such that it memorizes the data rather than finds the general correlations between the features. Eventually, the model might give perfect predictions on the training data, but when tested on real world inputs, it will fail terribly. A great example for overfitting is a powerful model that predicts housing prices but memorizes the exact adress instead of finding general correlation. This kind of model could do well on the test data, but since it is so powerful it simply memorizes the adress and color of a building and correlates it to the price instead of finding general rules in the data set.

What is a metric? How does it differ from "loss"?

How can pretrained models help?

What is the "head" of a model?

What kinds of features do the early layers of a CNN find? How about the later layers?

Are image models only useful for photos?

What is an "architecture"?

What is segmentation?

What is y_range used for? When do we need it?

What are "hyperparameters"?

What's the best way to avoid failures when using AI in an organization?

### 02 Production:

Provide an example of where the bear classification model might work poorly in production, due to structural or style differences in the training data.

- An app that should supposedly identify bears for users camping in the wilderness could be one example. The data used in production would most likely be significantly different from the training data. Some images might have very poor quality, lighting, be too far away, and possibly not even feature any bears. Apart from that, the use cases for such an app would also be quite limited since it's likely that only a very small demographic of people would actually go out of their way (and safety) to take a picture of a bear in the wilderness. On the other hand, if deployed and marketed as as a website for wilderness photographers used to verify their existing predictions about the type of bear they photographed, the tool might deem useful.

Where do text models currently have a major deficiency?

What are possible negative societal implications of text generation models?

In situations where a model might make mistakes, and those mistakes could be harmful, what is a good alternative to automating a process?

What kind of tabular data is deep learning particularly good at?

What's a key downside of directly using a deep learning model for recommendation systems?

What are the steps of the Drivetrain Approach?

How do the steps of the Drivetrain Approach map to a recommendation system?

Create an image recognition model using data you curate, and deploy it on the web.

What is DataLoaders?

What four things do we need to tell fastai to create DataLoaders?

What does the splitter parameter to DataBlock do?

How do we ensure a random split always gives the same validation set?

What letters are often used to signify the independent and dependent variables?

What's the difference between the crop, pad, and squish resize approaches? When might you choose one over the others?

What is data augmentation? Why is it needed?

What is the difference between item_tfms and batch_tfms?

What is a confusion matrix?

What does export save?

What is it called when we use a model for getting predictions, instead of training?

What are IPython widgets?

When might you want to use CPU for deployment? When might GPU be better?

What are the downsides of deploying your app to a server, instead of to a client (or edge) device such as a phone or PC?

What are three examples of problems that could occur when rolling out a bear warning system in practice?

What is "out-of-domain data"?

What is "domain shift"?

What are the three steps in the deployment process?

### 03 Ethics 

Does ethics provide a list of "right answers"?

How can working with people of different backgrounds help when considering ethical questions?

What was the role of IBM in Nazi Germany? Why did the company participate as it did? Why did the workers participate?

What was the role of the first person jailed in the Volkswagen diesel scandal?

What was the problem with a database of suspected gang members maintained by California law enforcement officials?

Why did YouTube's recommendation algorithm recommend videos of partially clothed children to pedophiles, even though no employee at Google had programmed this feature?

What are the problems with the centrality of metrics?

Why did Meetup.com not include gender in its recommendation system for tech meetups?

What are the six types of bias in machine learning, according to Suresh and Guttag?

Give two examples of historical race bias in the US.

Where are most images in ImageNet from?

In the paper "Does Machine Learning Automate Moral Hazard and Error" why is sinusitis found to be predictive of a stroke?

What is representation bias?

How are machines and people different, in terms of their use for making decisions?

Is disinformation the same as "fake news"?

Why is disinformation through auto-generated text a particularly significant issue?

What are the five ethical lenses described by the Markkula Center?

Where is policy an appropriate tool for addressing data ethics issues?